version: '3'
services:
  web:
    build: .
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules/
    ports:
      - 8080:8080
      - 3000:3000
    command: bash -c "npm start"
    restart: always